"""Labs content: every word a visitor reads on the Labs site.

Copy comes from John's Labs site (labs-rouge.vercel.app) and from each build's
own public page, captured 13 September 2026. Figures inside the stories are each
product's own published example or sample data, and every bay footer says which
one. The build refuses em and en dashes, so ranges read "8.5 to 19".

A build's phases are (tab, caption). Its story, in tools/stories.py (RideLens,
Daylight, RailDrop, shared with the portfolio) or tools/labs_stories.py (the four
builds only Labs tells), draws one state per phase; the counts must match.
`route` is the short link on this domain; vercel.json redirects it to `live`."""

SITE = dict(
    name='John Jayasankar',
    domain='https://labs-rouge.vercel.app',
    email='johnjayasankar@gmail.com',
    portfolio='https://johnjayasankar.com/',
    substack='https://substack.com/@johnjayasankar',
    linkedin='https://www.linkedin.com/in/johnjayasankar',
    city='New York',
    year='2026',
    title='Labs · John Jayasankar',
    description='Independent products John Jayasankar shipped: RideLens, Daylight, RailDrop, and other instruments.',
    og_description='Independent products, shipped.',
    og_image='/assets/img/og.jpg',
    og_alt='Labs · John Jayasankar · independent products, shipped',
    note='Independent products. Separate from the portfolio.',
)

BUILDS = [
    dict(
        slug='ridelens', n='01', name='RideLens', cat='Consumer', tag='Consumer', featured=True,
        line='Every ride, one comparison.',
        blurb='Live roads. Real rate cards. Uber, Lyft, Empower, and Curb ranked before you open four apps and guess.',
        does=['Map the trip once on live roads, then line up four providers side by side',
              'Rank the same quotes by Price, Soonest, or Value',
              'Estimates move with traffic, time of day, hotspots, and weather'],
        stats=[('4', 'providers, one board'), ('3', 'ways to rank a trip'), ('Honest', 'ranges stay ranges')],
        rule='Ranges stay ranges.',
        rule_body='When a fare is a range, both ends stay on the board. RideLens never invents a midpoint to look decisive.',
        words='Route Price Soonest Value Estimate Range Upfront',
        route='/ridelens', live='https://ride-lens2.vercel.app/', case='https://johnjayasankar.com/work/ridelens',
        bay=dict(title='RideLens · compare board', sub='Illustrative trip · four providers, three sort rules',
                 big='4 → 1', big_sub='providers → one board',
                 foot='Illustrative quote types, not live fares · the final fare is always confirmed in the provider app'),
        phases=[('Route', 'Illustrative: map the trip once on live roads; conditions feed the marketplace model.'),
                ('Price', 'Illustrative: the same four quotes, ranked by lowest listed fare.'),
                ('Soonest', 'Illustrative: the same quotes, ranked by soonest pickup.'),
                ('Value', 'Illustrative: fare and wait traded off. Ranges stay ranges.')],
    ),
    dict(
        slug='daylight', n='02', name='Daylight', cat='Native', tag='Native macOS', featured=True,
        line='Your screen, through the day.',
        blurb='Warmth and brightness on a schedule you set - gradual, offline, and honest about what it is doing and why.',
        does=['Shift warmth and brightness gradually on a schedule, or follow the sun',
              'Decide every control on one printed, six-layer ladder',
              'Read back after every write, and say so when another app took over'],
        stats=[('6', 'layers, one fixed order'), ('3', 'levels of certainty'), ('263', 'tests, no dependencies')],
        rule='Success is not evidence.',
        rule_body='Daylight separates what it asked for, what macOS accepted, and what it could read back and confirm.',
        words='Schedule Resolve Explain Asked Accepted Confirmed',
        route='/daylight', live='https://daylight-app-wine.vercel.app/', case='https://johnjayasankar.com/work/daylight',
        bay=dict(title='Daylight · display schedule', sub='Balanced preset · warmth and brightness decided separately',
                 big='6 layers', big_sub='one fixed order',
                 foot='Schematic · step values from the Balanced preset · the sentence is one the app writes'),
        phases=[('Schedule', 'Balanced preset: 6500 K by day, 4200 K at 19:00, 3200 K at 21:30, 2800 K at 23:30.'),
                ('Resolve', 'Six layers in a fixed order: the highest layer that speaks about a control wins it.'),
                ('Explain', 'An app rule holds warmth neutral while dimming still comes from the schedule, and a sentence says so.'),
                ('Confirm', 'Asked, accepted, confirmed: an API returning success is not evidence the display changed.')],
    ),
    dict(
        slug='raildrop', n='03', name='RailDrop', cat='Consumer', tag='Consumer', featured=True,
        line='Know when your train gets cheaper.',
        blurb='Book the trip. Watch every bookable Amtrak option across your window. One email when a listed fare actually drops.',
        does=['Watch every bookable rail option across the day before, the day, and the day after',
              'Scan immediately, then again morning, afternoon, and evening',
              'One email when a listed fare beats what you paid'],
        stats=[('±1 day', 'default watch window'), ('1 email', 'only when it improves'), ('0', 'invented prices')],
        rule='Never an invented price.',
        rule_body='If the live board is down, RailDrop says so. It never guesses a fare, a change fee, or an itinerary.',
        words='Booked Watching Board Alert Listed Honest',
        route='/raildrop', live='https://rail-drop3.vercel.app/', case='https://johnjayasankar.com/work/raildrop',
        bay=dict(title='RailDrop · Amtrak fare watch', sub='Sample board · BOS → NYP · you paid $128',
                 big='$128 → $47', big_sub='paid → cheapest listed',
                 foot='Sample board from RailDrop’s own site · listed fares · confirm on Amtrak'),
        phases=[('Booked', 'Illustrative: stations, date, and what you actually paid become the baseline.'),
                ('Watching', 'Illustrative: the first scan runs immediately, then morning, afternoon, and evening.'),
                ('Board', 'Illustrative: every bookable option across ±1 day, measured against what you paid.'),
                ('Alert', 'Illustrative: one email when a listed fare beats what you paid. Confirm on Amtrak.')],
    ),
    dict(
        slug='agentfit', n='04', name='AgentFit', cat='Model', tag='Decision model', featured=False,
        line='When should a workflow get an agent?',
        blurb='AgentFit scores economic opportunity, technical readiness, controllability, and risk before anyone writes an orchestration graph.',
        does=['Score fit from 0 to 100 across six weighted components',
              'Recommend autonomy separately, held down by 31 published gates',
              'Recommend deterministic automation or a human-led process when that is the answer'],
        stats=[('31', 'autonomy gates'), ('6', 'rungs, 0 to 5'), ('15', 'reference workflows')],
        rule='Fit is not autonomy.',
        rule_body='A workflow can score in the eighties and still warrant nothing beyond human-approved execution.',
        words='Fit Autonomy Readiness Capacity Gates Earned',
        route='/agentfit', live='https://agent-fit2.vercel.app/', case=None,
        bay=dict(title='AgentFit · worked example', sub='Support triage · the model’s published reference output',
                 big='78', big_sub='fit · autonomy decided apart',
                 foot='The reference output AgentFit publishes for Support triage · deterministic · nothing leaves the device'),
        phases=[('Fit', 'Six weighted components score the workflow: Support triage lands at 78.'),
                ('Autonomy', 'Autonomy is computed apart from fit, and gates hold it down: Supervised.'),
                ('Readiness', 'Readiness is its own track: Pilot ready, with instrumentation and an exception path.'),
                ('Verdict', 'Effort is always a range, 8.5 to 19. Plausible return, counted as capacity, not savings.')],
    ),
    dict(
        slug='cartonry', n='05', name='Cartonry', cat='Tool', tag='Tool', featured=False,
        line='Packaging dielines - cut, crease, fold, cost.',
        blurb='Production-ready packaging dielines at any size. Export SVG, true-scale PDF, and DXF. Runs entirely in your browser.',
        does=['Enter the internal size, and the board allowances are added on top',
              'Eleven box styles, from shipping cases to tuck-end cartons and pillow boxes',
              'A 3D fold built from the same geometry the dieline is cut from'],
        stats=[('11', 'box styles'), ('3', 'export formats'), ('2', 'styles free to export')],
        rule='Not a picture.',
        rule_body='The 3D fold is the geometry the dieline is cut from, and the tests fold the net and measure it against the dimensions typed.',
        words='Size Dieline Cut Crease Glue Fold',
        route='/cartonry', live='https://cartonry.vercel.app/', case=None,
        bay=dict(title='Cartonry · dieline', sub='Example · Regular Slotted Container 0201 · 200 × 150 × 100 mm',
                 big='747 × 253', big_sub='mm blank, from the internal size',
                 foot='The example on Cartonry’s own page · B-flute board, 3 mm · files are generated on your device'),
        phases=[('Size', 'Type the internal size, the space the product needs: 200 × 150 × 100 mm.'),
                ('Dieline', 'The blank is computed, with cut, crease, and glue on separate named layers.'),
                ('Check', 'Every part is listed, and the outside comes to 206 × 156 × 106 mm.'),
                ('Export', 'SVG, true-scale PDF, or DXF, generated on the device.')],
    ),
    dict(
        slug='keepfloor', n='06', name='KeepFloor', cat='Pricing', tag='Pricing', featured=False,
        line='The Etsy list price that still pays you.',
        blurb='One listing, the published fee stack, and the lowest charmed price that survives Offsite Ads. Math stays on this device.',
        does=['Every published Etsy fee, stacked line by line for one listing',
              'Three floors: organic, Offsite Ads safe, and survive-all',
              'Charm rounding, with the leftover shown and never counted as a fee'],
        stats=[('3', 'price floors'), ('7', 'published fee lines'), ('Local', 'math stays on this device')],
        rule='Every published fee, counted.',
        rule_body='The whole published fee stack, including Offsite Ads, then the lowest charmed list price that survives it.',
        words='Listing Fees Floors Keep Charm Ads',
        route='/keepfloor', live='https://keep-floor.vercel.app/', case=None,
        bay=dict(title='KeepFloor · one listing', sub='Example listing · Linen tote · US shop',
                 big='$19.08', big_sub='kept at a $32.00 list',
                 foot='The example listing on KeepFloor’s own page · rates as of 4 September 2026 · not affiliated with Etsy'),
        phases=[('Listing', 'One listing: a $32.00 list, $5.50 shipping charged, and the costs behind it.'),
                ('Fees', 'The published fee stack: $4.02 in Etsy-side fees on this order.'),
                ('Floors', 'Three floors: organic $24.99, ads-safe $30.99, survive-all $35.99.'),
                ('Keep', 'At $32.00 you keep $19.08, and the math stays on the device.')],
    ),
    dict(
        slug='pricing', n='07', name='Pricing Hub', cat='Workbook', tag='Workbook', featured=False,
        line='Contractor job costing, estimate to invoice.',
        blurb='Estimate, schedule, track crew hours and costs, handle change orders, invoice, and see real profit per job. 24 connected sheets for Excel and Google Sheets.',
        does=['Price a job line by line, then print a client-ready proposal',
              'Change orders with a signable form, invoices, and payments in one workbook',
              'Budget against actual per cost code, on a dashboard that keeps itself up to date'],
        stats=[('24', 'connected sheets'), ('893', 'formula checks in Excel'), ('0', 'macros or add-ins')],
        rule='Plain formulas only.',
        rule_body='No subscription, no add-ins, no macros. Every link between sheets is a real formula reference.',
        words='Estimate Sheets Margin Overrun Checks',
        route='/pricing', live='https://pricing-hub-seven.vercel.app/', case=None,
        bay=dict(title='Pricing Hub · job costing', sub='Profit check example · one job, one blended markup',
                 big='$46,831', big_sub='proposal total',
                 foot='The example on the product’s own Profit check · one blended markup · not accounting or tax advice'),
        phases=[('Estimate', 'Cost times markup, plus contingency: a $46,831 proposal.'),
                ('Connect', 'Every sheet feeds the next: setup, inputs, documents, reports.'),
                ('Overrun', 'A 10% overrun keeps $1,602 of the $5,288 net profit priced in.'),
                ('Checked', '893 formula checks and 46 bad-data probes. No macros, no add-ins.')],
    ),
]

HOME = dict(
    badge='Independent products · 2026',
    h1=('Instruments I shipped.', 'Built end-to-end. No demos.'),
    lede='Consumer tools, pricing engines, and a model for when a workflow should get an agent.',
    meta=['07 live', '03 featured', 'New York'],
    # the hero showcase keeps the Labs site's own framing: range, one bench
    show=[('consumer', '01 Consumer', 'ridelens'), ('native', '02 Native', 'daylight'), ('model', '03 Model', 'agentfit')],
    proof=[('7', 'live builds on one bench', '#featured'),
           ('4 → 1', 'ride providers, one RideLens board', '#ridelens'),
           ('31', 'autonomy gates in AgentFit', '#agentfit'),
           ('893', 'formula checks in Pricing Hub', '#pricing')],
    featured=dict(n='01', kicker='Featured', h2=('Three systems', 'that show the range.')),
    also=dict(n='02', kicker='Also shipped', h2=('Narrower instruments.', 'Same bar.')),
    rules=dict(n='03', kicker='What they share', h2=('No demos.', 'The rule each build keeps.')),
    visit=dict(k='johnjayasankar.com', h2='The portfolio.',
               lede='Production AI agents and 0→1 financial infrastructure, with case studies for RideLens, Daylight, and RailDrop.',
               link='Open the portfolio'),
    hint='j / k builds · Enter opens · 1-4 phases · ⌘K jump · ? keys',
)

NOT_FOUND = dict(
    kicker='Not found',
    h1=('Not a build.', 'Nothing lives at this address.'),
    lede='Every Labs build is below, one click from live.',
    hint='j / k builds · Enter opens · ⌘K jump',
)
